 
        <div class="art-blockheader">
            <h3 class="t">Descargas</h3>
        </div>
     <div class="descargas">
        <table border="0" cellpadding="5" cellspacing="0" align="center" width="600" font-color="black">
         <tbody><tr>
        <td align="center">
        <div style="background-color:#bd1d49; font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#FFF; padding:7px; border:2px solid #680621" align="justify">
        Esta es una lista de los software que usted puede descargar, los enlaces van directos a las paginas donde puede usted descargar directamente los software de manera segura. espero que sean de utilidad para todos los que nos visitan.
        </div>
        </td>
        </tr>
        <tr>
        <td align="center">
        <table border="0" cellpadding="4" cellspacing="8" align="center" width="490">	<tbody><tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/opera.png" border="0"></td></tr><tr><td align="center"><a href="http://www.opera.com/" target="_blank" class="autor">Opera</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/mozillafirefox.png" border="0"></td></tr><tr><td align="center"><a href="http://www.mozilla-europe.org/es/firefox/" target="_blank" class="autor">Mozilla Firefox</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/googlechrome.png" border="0"></td></tr><tr><td align="center"><a href="http://www.google.com/chrome" target="_blank" class="autor">Google Chrome</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/safari.png" border="0"></td></tr><tr><td align="center"><a href="http://www.apple.com/safari/" target="_blank" class="autor">Safari</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/skype.png" border="0"></td></tr><tr><td align="center"><a href="http://www.skype.com/intl/es/home" target="_blank" class="autor">Skype</a></td></tr></tbody></table></td></tr>
	<tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/yahoomessenger.png" border="0"></td></tr><tr><td align="center"><a href="http://es.messenger.yahoo.com/" target="_blank" class="autor">Yahoo! Messenger</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/mozillathunderbird.png" border="0"></td></tr><tr><td align="center"><a href="http://www.mozillamessaging.com/es-ES/" target="_blank" class="autor">Mozilla Thunderbird</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/googletalk.png" border="0"></td></tr><tr><td align="center"><a href="http://www.google.com/talk/intl/es/" target="_blank" class="autor">Google Talk</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/digsby.png" border="0"></td></tr><tr><td align="center"><a href="http://www.digsby.com/" target="_blank" class="autor">Digsby</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/pidgin.png" border="0"></td></tr><tr><td align="center"><a href="http://pidgin.im/" target="_blank" class="autor">Pidgin</a></td></tr></tbody></table></td></tr>
	<tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/avgfreeantivirus.png" border="0"></td></tr><tr><td align="center"><a href="http://free.avg.com/" target="_blank" class="autor">AVG Free Anti-Virus</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/avastantivirushome.png" border="0"></td></tr><tr><td align="center"><a href="http://www.avast.com/es-ww/free-antivirus-download" target="_blank" class="autor">Avast Antivirus Home</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/aviraantivirpersonal.png" border="0"></td></tr><tr><td align="center"><a href="http://www.free-av.de/es/trialpay_download/1/avira_antivir_personal__free_antivirus.html" target="_blank" class="autor">Avira AntiVir Personal</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/zonealarm.png" border="0"></td></tr><tr><td align="center"><a href="http://www.zonealarm.es/security/es/anti-virus-spyware-free-download.htm" target="_blank" class="autor">ZoneAlarm</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/malwarebytesantimalware.png" border="0"></td></tr><tr><td align="center"><a href="http://www.malwarebytes.org/mbam.php" target="_blank" class="autor">Malwarebytes' Anti-Malware</a></td></tr></tbody></table></td></tr>
	<tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/security360.png" border="0"></td></tr><tr><td align="center"><a href="http://www.iobit.com/download.html#freesoftware" target="_blank" class="autor">Security 360</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/adawarefreeantimalware.png" border="0"></td></tr><tr><td align="center"><a href="http://www.lavasoft.com/products/ad_aware_free.php" target="_blank" class="autor">Ad-Aware Free Anti-Malware</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/advancedsystemcarefree.png" border="0"></td></tr><tr><td align="center"><a href="http://www.iobit.com/advancedwindowscareper.html" target="_blank" class="autor">Advanced SystemCare Free</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/ccleaner.png" border="0"></td></tr><tr><td align="center"><a href="http://www.piriform.com/ccleaner" target="_blank" class="autor">CCleaner</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/smartdefrag.png" border="0"></td></tr><tr><td align="center"><a href="http://www.iobit.com/iobitsmartdefrag.html" target="_blank" class="autor">Smart Defrag</a></td></tr></tbody></table></td></tr>
	<tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/defraggler.png" border="0"></td></tr><tr><td align="center"><a href="http://www.piriform.com/defraggler" target="_blank" class="autor">Defraggler</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/openoffice.png" border="0"></td></tr><tr><td align="center"><a href="http://es.openoffice.org/" target="_blank" class="autor">OpenOffice</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/cutepdfwriter.png" border="0"></td></tr><tr><td align="center"><a href="http://www.cutepdf.com/" target="_blank" class="autor">CutePDF Writer</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/adobereader.png" border="0"></td></tr><tr><td align="center"><a href="http://get.adobe.com/es/reader/" target="_blank" class="autor">Adobe Reader</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/realplayer.png" border="0"></td></tr><tr><td align="center"><a href="http://es.real.com/realplayer/" target="_blank" class="autor">Real Player</a></td></tr></tbody></table></td></tr>
	<tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/appleitunes.png" border="0"></td></tr><tr><td align="center"><a href="http://www.apple.com/mx/itunes/download/" target="_blank" class="autor">Apple iTunes</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/vlcmediaplayer.png" border="0"></td></tr><tr><td align="center"><a href="http://www.videolan.org/" target="_blank" class="autor">VLC Media Player</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/audacity.png" border="0"></td></tr><tr><td align="center"><a href="http://audacity.sourceforge.net/" target="_blank" class="autor">Audacity</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/winamp.png" border="0"></td></tr><tr><td align="center"><a href="http://www.winamp.com/media-player/download/es" target="_blank" class="autor">Winamp</a></td></tr></tbody></table></td>
<td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100" height="100" class="t_app"><tbody><tr><td align="center" heigth="80"><img src="images/picasa.png" border="0"></td></tr><tr><td align="center"><a href="http://picasa.google.com/" target="_blank" class="autor">Picasa</a></td></tr></tbody></table></td></tr>
</tbody></table><div align="center" style="background-color:#bd1d49; font-family:Arial, Helvetica, sans-serif; font-size:18px; color:#FFF; padding:7px; border:2px solid #680621" id="paginador"><p align="center"><span>1</span> | <a href="#">2</a> | <a href="#"><img src="images/siguiente.png" border="0"></a> | <a href="#"><img src="images/ultimo.png" border="0"></a></p><p align="center">Mostrando Información desde el 1 hasta el 30 de un total de 60</p></div> </td>
        </tr>
        </tbody></table> 
           </div>